version: '3.8'

services:
  etl-agent:
    image: iampruh887/etl-agent:latest
    container_name: etl-agent
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./data:/app/data:ro
      - ./output:/app/output
      - ./logs:/app/logs
    stdin_open: true
    tty: true
    command: --help

  etl-agent-interactive:
    image: iampruh887/etl-agent:latest
    container_name: etl-agent-interactive
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./data:/app/data:ro
      - ./output:/app/output
      - ./logs:/app/logs
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash"]
